deployment:
  replicas: 2
  imageVersion: IMAGE_VERSION
  imageURL: 805778285734.dkr.ecr.us-east-1.amazonaws.com/roboshop/dev/frontend
hpa:
  cpuUtilization: 15
tgb:
  arn: arn:aws:elasticloadbalancing:us-east-1:805778285734:targetgroup/roboshop-dev/c7a76e34af37095c
  